version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}

    ports:
      - "${RABBITMQ_AMPQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"

    volumes:
      - data:/var/lib/rabbitmq
      - logs:/var/log/rabbitmq

volumes:
  data:
  logs:
